// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _18TWENTY8.Models;

namespace _18TWENTY8.Migrations
{
    [DbContext(typeof(EighteentwentyeightContext))]
    [Migration("20210309143333_changetypepub")]
    partial class changetypepub
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_18TWENTY8.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.ToTable("ApplicationRole");
                });

            modelBuilder.Entity("_18TWENTY8.Models.PressPublicity", b =>
                {
                    b.Property<int>("PressPubID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Description");

                    b.Property<string>("Pathurl");

                    b.Property<int>("PressPubTypeID");

                    b.Property<string>("SiteUrl");

                    b.Property<string>("Title");

                    b.HasKey("PressPubID");

                    b.ToTable("PressPublicity");
                });

            modelBuilder.Entity("_18TWENTY8.Models.PressPubType", b =>
                {
                    b.Property<int>("PressPubTypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Description");

                    b.HasKey("PressPubTypeID");

                    b.ToTable("PressPubType");
                });
#pragma warning restore 612, 618
        }
    }
}
